services:
  # Backend API Service
  - type: web
    name: ecardamom-backend
    env: node
    region: oregon # Change to your preferred region
    plan: free # or starter/standard
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false # Set in Render Dashboard
      - key: JWT_SECRET
        sync: false # Set in Render Dashboard
      - key: USE_GMAIL
        value: true
      - key: SMTP_SECURE
        value: true
      - key: SMTP_PORT
        value: 465
      - key: SMTP_USER
        sync: false # Set in Render Dashboard
      - key: SMTP_PASS
        sync: false # Set in Render Dashboard
      - key: MAIL_FROM
        sync: false # Set in Render Dashboard
      - key: FRONTEND_URL
        sync: false # Set in Render Dashboard
